#!/usr/bin/env node
/**
 * Vendor the CLIENT-side moral core from conscience-research (the single
 * source of truth, measured by the clinical trial) into this plugin.
 *
 *   node scripts/sync-core.mjs [path-to-conscience-research]
 *
 * System 0 (the reflex), script resolution and download sizing, edge
 * redaction, and the NormalizedCall codec. Copied verbatim as CommonJS — the
 * hook is a plain Node script — and stamped with the source commit so every
 * call the service receives says which reflex passed it.
 */
import { execSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(process.argv[2] ?? join(HERE, '..', '..', 'conscience-research'));
const HARNESS = join(SRC, 'tests', 'harness');
const CORE = join(HERE, '..', 'lib', 'core');
const MODULES = ['system0.js', 'context-client.js', 'redact.js', 'normalize.js'];

const sha = execSync('git rev-parse --short HEAD', { cwd: SRC }).toString().trim();
const dirty = execSync('git status --porcelain -- tests/harness', { cwd: SRC }).toString().trim() ? '-dirty' : '';

mkdirSync(CORE, { recursive: true });
for (const name of MODULES) {
	const src = readFileSync(join(HARNESS, name), 'utf8');
	for (const m of src.matchAll(/require\('\.\/([\w-]+)'\)/g)) {
		if (!MODULES.includes(`${m[1]}.js`)) throw new Error(`${name} requires ./${m[1]}, which is not vendored`);
	}
	writeFileSync(join(CORE, name), `// VENDORED from conscience-research/tests/harness/${name} by scripts/sync-core.mjs — do not edit here.\n${src}`);
	console.log(`  lib/core/${name}`);
}
writeFileSync(join(CORE, 'version.js'), `// Generated by scripts/sync-core.mjs — do not edit.\nmodule.exports = { CORE_SHA: '${sha}${dirty}', CORE_SYNCED_AT: '${new Date().toISOString()}' };\n`);
console.log(`  lib/core/version.js → ${sha}${dirty}`);
